### PR TITLE
Update holvi-master with current master with Django back compatibility [EXP-167]

### PR DESCRIPTION
**Pull request by abramovholvi**
## What's done
1. Synced the latest https://github.com/django-waffle/django-waffle master
2. Merged new master to our holvi-master copied branch keeping logic added by @holvianssi @grastenis @harrastia (only didn't not keep support for callback introduced in https://github.com/holvi/django-waffle/pull/2/files because couldn't find it used anywhere in Vault. Can add if needed.
3. Manually reverting a commit where support for `Django < 1.11` was dropped (https://github.com/django-waffle/django-waffle/commit/3efa0e6874c2485e4b88f71882d678f63e9f808a)
4. Fixed tests, now if you run `tox` all tests should pass

### CODE REVIEW

**Review by holvi-anastasiia — COMMENTED** [review]
@abramovholvi looks good! Have you run vault tests with updated waffle?

**Comment by abramovholvi** [comment]
Yes, I did run tests locally and created this PR with adjustments that need to be done to let vault work correctly with both old and new versions: https://github.com/holvi/vault/pull/6446

**Review by harrastia — APPROVED** [review]
Quite a few changes and difficult to review, however the reversion of commit and update of migrations look good.
About the migrations, did we add some migrations in our patches to waffle? if not I guess we should take whatever came in, or are they not compatible anymore? Thing is that that 0002 migration is already applied and may then fail if we try applying it again. We could bring this in a prepare a release so vault changes can be tested against this.

**Review by harrastia — CHANGES_REQUESTED** [review]
Sorry I think we need to patch also the migrations to adjust to our custom user model, otherwise one of the new migrations may screw up things. Please see and our tweaked migration 0002

https://github.com/holvi/django-waffle/blob/bf5fd6856544fd8c44ed9f28d9ea41cad1523c5b/waffle/migrations/0004_update_strings_for_i18n.py#L95

**Comment by abramovholvi** [comment]
Thanks @harrastia for catching a problem! Fixed now.
Also related to your question about existing migrations: 0002_auto_20160616_1224 is already applied, so we will just apply two new ones after it.

**Review by harrastia — APPROVED** [review]

**Comment by harrastia** [comment]
Let's bring this in, we can always recover and build old version in case of need

**Pull request merged**
